### ISSUE TITLE
Game crashes when trying to load settings_data.json

### ISSUE THREAD

**Issue by ParkourNinjaKitty** [PunchablePlushie/godot-game-settings#18]
I went through all of the required setup steps and I looked through ggs_manager.gd and I can't seem to find an issue. When I delete the settings_data.json from my app data and run the program it crashes when I open my options menu. A settings_data.json file is created fine when running in the editor but when I build it for windows, it creates an empty json in the right location with the right name.

**Comment by PunchablePlushie** [comment]
Sorry about the issue but unfortunately, I won't be working on 2.x issues anymore as I'm working on the 3.0 update which will completely deprecate 2.x.
I plan to (hopefully) release 3.0 by the end of this summer but this is a soft deadline and it may change depending on how things go.
