### ISSUE TITLE
Crash when add category

### ISSUE THREAD

**Issue by scriptsengineer** [PunchablePlushie/godot-game-settings#22]
res://addons/ggs/editor/category_panel/category_panel.gd:38 - Invalid call. Nonexistent function 'add_item' in base 'Tree ()'.

**Comment by PunchablePlushie** [comment]
Please make sure the "GGS" is in the autoload list and enabled. If it is, restart your project and see if that'll solve the issue. Check out [this](https://github.com/PunchablePlushie/godot-game-settings/wiki/TroubleShoot#i-cant-add-categories-or-generally-use-the-plugin-after-installation) for more info.

Let me know if that solved the issue.
