### ISSUE TITLE
Window moves to secondary monitor when changing resolution

### ISSUE THREAD

**Issue by nhandy** [PunchablePlushie/godot-game-settings#24]
When starting a game with the Display Size setting it moves the window to my secondary monitor. This still happens when I drag the window back to the main monitor and then change the resolution. The resolution changes but the window moves to the second monitor. I've also noticed that it appears to center it according to the dimensions of the primary monitor but on the secondary monitor. With this being that case much of the window is off screen (my primary monitor is much larger).

Any thoughts on what's doing this and if it's maybe an issue with my implementation?

**Comment by Norodix** [comment]
See:
https://github.com/PunchablePlushie/godot-game-settings/pull/27

**Comment by nhandy** [comment]
Applied the changes to my version and it works now, thx so much!

**Comment by PunchablePlushie** [comment]
Fixed in #27.
