### ISSUE TITLE
Cannot remap inputs to arrow keys

### ISSUE THREAD

**Issue by Norodix** [PunchablePlushie/godot-game-settings#28]
Trying to remap some inputs to arrow keys causes the right and left arrow to be saved as B and X respectively.

I suspect this occurs during saving or loading because setting it behaves normally. Exiting the setting menu and going back overwrites left and right with X and B.

I noticed it in our game, but I also tested it in the GGS demo, it happens just the same.

Steps to reproduce: 
 - Start the demo UI
 - Set move inputs to the respective arrows
 - close the ui
 - start the UI again, observe the left and right input names

**Comment by kingoftheconnors** [comment]
I was confused by this as well. Why do input classes have types if they aren't used in sensing the action type? I'd either remove the Type so an InputButton can be mapped to anything, or pass the Type into the ggs_input_helper to make sure mix-ups like this can't happen.

**Comment by Norodix** [comment]
I think it is because usually games have the gamepad and kb+mouse settings coexisting.
Most games do it this way, I think that makes perfect sense.

Maybe to prevent future mixups the settings can be stored as input type+index instead of a string.
But even this is not necessary, as long as there is no name overlap everything works correctly.

**Comment by PunchablePlushie** [comment]
I've changed the gamepad keywords and updated the wiki. This should fix the issue as suggested by previous replies. (See 8b2192f)
Thank you for bringing this up and providing the solution.

**Comment by Norodix** [comment]
Happy to help! Thank you again for the great plugin!
