### ISSUE TITLE
File tree walking

### ISSUE THREAD

**Issue by halotroop2288** [PunchablePlushie/godot-game-settings#33]
Please add tree walking to the setting file discovery script. I would like to organize the setting scripts by category. It currently [only searches for files in one specific directory](https://github.com/PunchablePlushie/godot-game-settings/blob/6bbbcfaf623be988b5ec42f3ee25331a5f1b1af1/addons/ggs/editor/add_setting_window/add_setting_window.gd#L97), without checking sub-directories.

**Comment by PunchablePlushie** [comment]
I'll look into for 3.1.
