### ISSUE TITLE
Can't find link or repository to the 3.x version

### ISSUE THREAD

**Issue by zaknafean** [PunchablePlushie/godot-game-settings#37]
I was wanting to look at and reference the 3.x project that I'm currently using, but I've been unable to find any sign of it at all. Does it still exist in some form?

**Comment by PunchablePlushie** [comment]
Sadly, GGS 2 (which was for Godot 3) is no longer available even as part of the commit history as I had to hard push changes when updating to GGS 3, erasing GGS 2 and GGS 1 in the process.
So GGS 2 along with its documentation are not available anymore, and GGS for Godot 3 is no longer supported in general.

**Comment by zaknafean** [comment]
Tough for us with games in production using it... I suppose forks exist and
I'll just have to document it out myself for people using it still.
