### ISSUE TITLE
item_order not getting set

### ISSUE THREAD

**Issue by kingoftheconnors** [PunchablePlushie/godot-game-settings#38]
I created a new category "Assist Mode" in my game, and added three custom-made settings to it. However, whenever running the game, these settings would get reset to their default. When opening up the plugin_data.tres, I found the category:

```
[sub_resource type="Resource" id="Resource_8kxsx"]
resource_name = "AssistMode"
script = ExtResource("1_8aw2k")
name = "AssistMode"
settings = {}
item_order = Array[Resource("res://addons/ggs/classes/resources/ggs_setting.gd")]([])
```

It looks like the item_order isn't getting properly set, even though I added the settings to the category. Any ideas why?

![image](https://github.com/PunchablePlushie/godot-game-settings/assets/23728939/0117d5ac-17c4-4203-95b5-f0558437ee15)

This image was taken when the settings were first added. After closing Godot and reopening the project, the settings were gone.

**Comment by kingoftheconnors** [comment]
It may also be worth mentioning the "AssistMode" resource was placed at the very top of the plugin_data file, making it not able to refer to any other resources

**Comment by PunchablePlushie** [comment]
Unfortunately 3.0 and 3.1 may not longer be getting updates. Please consider using the latest 3.2 version when it's released.
