### ISSUE TITLE
godot 4.2 beta4 have a error

### ISSUE THREAD

**Issue by vmjcv** [PunchablePlushie/godot-game-settings#45]
When running the project using Godot 4.2 beta 4, there will be an error when adding the UI settings:

![image](https://github.com/PunchablePlushie/godot-game-settings/assets/25278695/31a28ce0-fca0-459f-8da2-4cbca8e2adb4)

Original code
```
func _on_List_item_activated(item_index: int) -> void:
	var EI: EditorInterface = ggsUtils.get_editor_interface()
	var ES: EditorSelection = EI.get_selection()
```

If you modify the code like this, it will run normally:
```
func _on_List_item_activated(item_index: int) -> void:
	var EI = ggsUtils.get_editor_interface()
	var ES = EI.get_selection()
```

**Comment by PunchablePlushie** [comment]
Unfortunately 3.0 and 3.1 may not longer be getting updates. Please consider using the latest 3.2 version when it's released.
