### ISSUE TITLE
Slider can override setting value hint string range

### ISSUE THREAD

**Issue by SlimFishyy** [PunchablePlushie/godot-game-settings#48]
I don't know if it's intended, but apply(value) can still take values higher that 0,1 range from slider. Maybe slider should change it's min/max values based on it's resource?
My setting:
![image](https://github.com/PunchablePlushie/godot-game-settings/assets/73362213/bd1cc050-88c9-4ab8-8185-2988d945f96e)
Values from slider:
![image](https://github.com/PunchablePlushie/godot-game-settings/assets/73362213/073561f8-edd9-499f-a977-c0e87fd97900)

**Comment by PunchablePlushie** [comment]
The value hint and hint string properties customize the way the properties are exported to the inspector, and they use Godot's built-in behavior with `_get_property_list()`. They have no control over the actual values of the exported properties or the `apply()` method.
