### ISSUE TITLE
[Suggestion] Trim whitespaces in scripts to follow Godot's official formatting

### ISSUE THREAD

**Issue by Visssarion** [PunchablePlushie/godot-game-settings#54]
Although not included in [GDScript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html), whitespace is being checked for in some of the official Godot's repositories.

[Godot's formatting check shell script.](https://github.com/godotengine/godot-demo-projects/blob/master/file_format.sh)

Adding this would be simple:
In Editor settings -> Text Editor -> Behaviour -> Trim Trailing Whitespace on Save should be set to ``true``. Resaving all scripts would guarantee removal of whitespace characters.

Not an impactful change, but would prevent users with aforementioned setting set to true to have to apply changes to their version control.

**Comment by PunchablePlushie** [comment]
Thanks for the suggestion. The Editor itself also recommends trimming the whitespace when I looked at the setting you mentioned.
I've enabled it and trimmed all existing scripts in the plugin. Changes were pushed to **export-fix**.
