### ISSUE TITLE
Fullscreen's "Size Setting" is throwing an error when not null

### ISSUE THREAD

**Issue by Visssarion** [PunchablePlushie/godot-game-settings#58]
Versions tested on: ``3.2.1``, ``3.2.0``

Setting "Size Setting" inside of Fullscreen Setting Resource results in:
- Error ``Trying to assign value of type 'int' to a variable of type 'String'.`` when running the scene
- Error ``Trying to assign value of type 'bool' to a variable of type 'String'.`` when flipping the fullscreen switch
on a line 29 of ``setting_display_fullscreen.gd``

Minimal Reproduction Demo:
[ggs-fullscreen.zip](https://github.com/user-attachments/files/17585691/ggs-fullscreen.zip)

**Comment by Visssarion** [comment]
Also, fullscreen setting uses ``MODE_FULLSCREEN``, which causes 1px border around application. Using ``MODE_EXCLUSIVE_FULLSCREEN`` instead fixes it.

From [here](https://github.com/godotengine/godot/issues/97435):
> * This is intentional and done to ensure multiwindow interface works in fullscreen (`MODE_FULLSCREEN` is only intended for GUI apps like Godot editor itself, not for games).
> 
> * For everything else, use `MODE_EXCLUSIVE_FULLSCREEN` (naming is bad, this mode is fully equivalent to 3.x `MODE_FULLSCREEN`).
> 
> * I'm pretty sure it is the same in 4.2 (and other 4.x), but border was always black, now it's using `clear color` from project settings.

**Comment by PunchablePlushie** [comment]
I've changed the issues you've mentioned. Everything should be fine in the latest push to the `3.2` branch.
